### ISSUE TITLE
Browsing directory: skip ".", allow up-arrow for parent

### ISSUE THREAD

**Issue by wmertens** [RoyalBingBong/meView#10]
When pressing <kbd>up</kbd>, you get a directory browser, neat! But, it has an entry for ".", which is useless, and if you want to go to the parent you have to press <kbd>enter</kbd> on the ".." instead of pressing <kbd>up</kbd> again when the cursor is at the top of the list…

**Comment by RoyalBingBong** [comment]
You can use the <kbd>Left-Arrow</kbd> to go up and <kbd>Right-Arrow</kbd> to go into a directory. If you have `.` selected and press <kbd>Right-Arrow</kbd>, you will open the directory you are currently in. Hold <kbd>Shift</kbd> when pressing <kbd>Ender</kbd> or <kbd>Right-Arrow</kbd> to open the selected directory recursive.
