### ISSUE TITLE
feature Window->minimize fails

### ISSUE THREAD

**Issue by rweissgh** [RoyalBingBong/meView#11]
Minimizing the window of meView does not bring me seamless viewing of images and videos but meView disappeares from the screen, leaving it in the task bar (Win 7 Ultimate).

:) rweiss

**Comment by RoyalBingBong** [comment]
What do you mean? Minimizing is supposed to hide the window and "put it in the task bar". Does it not restore back to the window if you click the task bar icon? Can you give me a more detailed run-down of your process?
