### ISSUE TITLE
[Feature Request] Open image passed through command line parameter

### ISSUE THREAD

**Issue by Andrey-dc** [RoyalBingBong/meView#2]
Hello
Please add ability to open file passed through command line, so that
C:\Path2meView\meView.exe C:\Path2img\myFile.webm
would open myFile.webm when meView starts.
Right now meView starts with no file opened (i'm on Windows7x64, not sure that it happens everywhere).

That would allow to configure external apps to conveniently send files to meView, in my case that would be Total Commander and FastStoneViewer.

**Comment by RoyalBingBong** [comment]
You actually can pass files into meView, but I hid that behind a switch (`-meview-open <pathtofileorfolder>`). In hindsight that was just stupid workaround.

The next release will remove that switch and do it the sane way: `meView.exe path/to/the/file.webm`.
