### ISSUE TITLE
Photos are randomly rotated at times.

### ISSUE THREAD

**Issue by ChildishhAlbino** [RoyalBingBong/meView#20]
Opening a folder results in some of the photos not displaying the correct orientation (some photos that are meant to be landscape are portrait and visa versa). Seemingly only applies to images that have had their orientation / rotation edited via the Windows Photos app.

Not sure where the bugs is but thought I'd post it. 

Cheers.

**Comment by RoyalBingBong** [comment]
That is surprisingly less trivial than I thought! Firefox can do this with simple CSS: `image-orientation: from-image;`, but Chrome can not...  
The Windows Photo app writes the orientation into the EXIF data, so I would have to read that data from the image and determine the rotation that way. There are aa couple of npm packages out there that can read the EXIF data, I just have to find one that fits my needs (or do my own thing).

**Comment by ChildishhAlbino** [comment]
Closing as the project is abandoned. I made a fix PR but have since closed it as I don't have the time to maintain it and the project no longer fits my personal needs. 

Please refer to the PR and build the project locally if you wish to use my fix.
