### ISSUE TITLE
Command line arguments - relative paths don't work

### ISSUE THREAD

**Issue by gladstonedigital** [RoyalBingBong/meView#3]
Platform: Debian 9 x86_64, kernel 4.9.0-3-amd64
meview version: 1.3.1 amd64

I have a folder of wallpapers: /home/user/Pictures/wallpapers

If I open a file like `meview /home/user/Pictures/wallpapers/wall01.jpg` it works perfectly fine. However if I do:
```
cd /home/user/Pictures/wallpapers
meview wall01.jpg
```
does not work. Neither does `meview ./wall01.jpg`. In both of these latter two cases, meview opens up but does not display an image. In the case of `meview wall01.jpg` it displays a gray background with an icon in the upper left indicating the file couldn't be found. In the case of `meview ./wall01.jpg` it displays a gray background with no icon in the left.

This seems to be an issue with relative vs absolute paths, as absolute paths work fine but relative paths don't seem to work at all.

**Comment by RoyalBingBong** [comment]
Workaround is already pushed, but I will wait with a release until I have worked on your other suggestions.
