### ISSUE TITLE
[Feature Request] A few command line ideas

### ISSUE THREAD

**Issue by gladstonedigital** [RoyalBingBong/meView#4]
It'd be nice to have more accessible command line arguments, like:
```
-h, --help
    Prints this help message and exits meview

-f, --fullscreen
    Opens meview in fullscreen automatically

-s, --slideshow [timer]
    Starts meview in slideshow mode, with **timer** seconds between each image (default 7)

-r, --recursive
    Open files from all subdirectories in addition to the top level directory
```

I'm sure there's many more useful command line options to have but these are a few I could think of.

**Comment by gladstonedigital** [comment]
A few more ideas:
    -a random/shuffle mode
    -make the mouse disappear when in fullscreen and not being moved
    -different scaling options like stretch, fill, fit, etc

Maybe take a look at the options that the image viewer feh offers and get some ideas from that?

Thanks for taking my suggestions! This is a great app and one of the only that I've found that can do webm, mp4, gif, jpg, png all in the same program.

**Comment by RoyalBingBong** [comment]
> -different scaling options like stretch, fill, fit, etc

I will put a hold on this (for now), because I intented meView to be a "basic" viewer for videos and images. IMO there are better alternatives if you want read comics or mangas.
