### ISSUE TITLE
MeView ignores files ending in .JPG (capitalized) in directory

### ISSUE THREAD

**Issue by gladstonedigital** [RoyalBingBong/meView#6]
Sorry for spamming you with so many issues, but I like this software and while using it I keep finding things to improve.

MeView seems to ignore files ending with .JPG; I'm assuming it's hardcoded to look for only certain file extensions and it only checks for lowercase?

**Comment by RoyalBingBong** [comment]
> I'm assuming it's hardcoded to look for only certain file extensions and it only checks for lowercase?

Exactly that! Fix is pushed. Release will take a bit, because I want to also fix #5 before making a new release.

> Sorry for spamming you with so many issues

No problem, I'm actually glad that someone is using meView at all 😄
